Feature/remove legacy auth
ONSdigital/florence pull request #1081
Opened 2024-12-06 15:15 UTC by mr-nick17

### What

Removed env config `ENABLE_NEW_SIGN_IN` 
Updated logic to handle removal of ⬆️ config
Removed legacy auth code
🤞 Fixed component tests so they run...

### How to review

Sense check
CI integration passes
Pull this branch, port forward to publishing api router on sandbox, login and check all new auth world still works ok

### Who can review

Frontend dev

2024-12-11 16:31 UTC, cookel2 requested changes
I haven't tested it yet but I've found a few typos.

2024-12-12 08:20 UTC, mr-nick17 commented on src/app/utilities/http-methods/request.test.js
> +        return new Promise((resolve, reject) => {
Disagree, a promise resolves or rejects. You do not have to define what it does in the class definition as that's up to the calling function to handle it https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

2024-12-12 08:20 UTC, mr-nick17 commented on src/app/utilities/http-methods/request.test.js
> +        return new Promise((resolve, reject) => {
See similar comment

2024-12-12 08:21 UTC, mr-nick17 commented on src/app/views/collections/details/CollectionDetailsController.jsx
> +                const newActiveCollection = updateEmailInActiveCollection[state].map(collectionPage => {
Possibly but as these changes had poor test coverage I am reluctant to change the logic beyond removing the feature toggle

2024-12-12 08:28 UTC, mr-nick17 commented on src/app/config/groups/thunks.js
> +                isDismissable: true,
Whilst I agree that this is indeed a typo. My change is to remove the feature flag. To change this typo there would need to be changes across the app. I suggest this should be a bug fix for the future depending on priorities etc. especially as Florence is considered legacy

2024-12-12 09:18 UTC, mr-nick17 commented on src/app/utilities/api-clients/user.js
> +                                isDismissable: true,
As above, invasive change

2024-12-12 09:19 UTC, mr-nick17 commented on src/app/utilities/api-clients/user.js
> +                    isDismissable: true,
As above, invasive change

2024-12-12 15:23 UTC, cookel2 approved these changes
It tested successfully - LGTM.

2024-12-12 16:49 UTC, merged