925: Login fails after going from new login to old login
ONSdigital/florence pull request #872
Opened 2022-07-25 12:16 UTC by joegasewicz

### What

Toggling between the new login and the old login fails due to to existence of the tokens.

### How to review

1. Enable the JWT sessions (zebedee) and new sign in (florence) feature flags
2. Login
3. Disable the two above feature flags
4. Attempt to log in again

### Who can review

Anyone

Describe who worked on the changes, so that other people can review.
myself

2022-07-25 19:20 UTC, cookel2 requested changes

2022-07-26 10:32 UTC, joegasewicz commented on service/service.go
> +	cantabularMetadataExtractorAPIProxy := reverseproxy.Create(apiRouterURL, directors.FixedVersionDirector(cfg.APIRouterVersion, ""), nil)
Sorry this is just my linter updating this line, its not part of the PR

2022-07-26 10:33 UTC, joegasewicz commented on src/app/utilities/api-clients/user.js
> +        return http.delete("/cookies");
These are defaulted to false which is what i require but thank you, good check!

2022-07-26 13:03 UTC, cookel2 approved these changes
looks good to me

2022-07-26 13:05 UTC, merged